# Generated by Django 5.2.5 on 2025-09-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_profile_pic'),
    ]

    operations = [
    ]
