# Generated by Django 5.2.9 on 2026-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='popular',
            field=models.BooleanField(default=False, help_text='If checked, item will appear on home page'),
        ),
    ]
