# Generated by Django 5.2.5 on 2025-09-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_actual_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimate_delivery_time',
        ),
    ]
