# Generated by Django 5.2.5 on 2025-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_actual_delivery_time_order_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On the way'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status: pending / on_the_way / completed / cancelled', max_length=20),
        ),
    ]
