# Generated by Django 5.2.5 on 2025-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, help_text="Stores 'user (username)' or 'admin' if cancelled", max_length=100, null=True),
        ),
    ]
